### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by jarradh** [syng-io/syng-client#15]
08-11 01:06:08.092  19432-19504/? E/AndroidRuntime﹕ FATAL EXCEPTION: HandlerThread
    Process: io.syng, PID: 19432
    java.lang.ClassCastException: android.os.Parcelable[] cannot be cast to org.ethereum.core.TransactionReceipt[]
            at org.ethereum.android.service.events.BlockEventData.<init>(BlockEventData.java:63)
            at org.ethereum.android.service.events.BlockEventData$1.createFromParcel(BlockEventData.java:50)
            at org.ethereum.android.service.events.BlockEventData$1.createFromParcel(BlockEventData.java:46)
            at android.os.Parcel.readParcelable(Parcel.java:2246)
            at android.os.Parcel.readValue(Parcel.java:2146)
            at android.os.Parcel.readArrayMapInternal(Parcel.java:2479)
            at android.os.BaseBundle.unparcel(BaseBundle.java:221)
            at android.os.BaseBundle.getSerializable(BaseBundle.java:988)
            at android.os.Bundle.getSerializable(Bundle.java:894)
            at io.syng.fragment.ConsoleFragment.handleMessage(ConsoleFragment.java:122)
            at org.ethereum.android.service.ServiceConnector$IncomingHandler.handleMessage(ServiceConnector.java:64)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:145)
            at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by jarradh** [comment]
I recursively pulled and still get the issue by tappin on Cow then tapping on Cow in profile list

**Comment by jarradh** [comment]
Yaroslav reproduced error also, but only on console
