### ISSUE TITLE
SecurityException: requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS

### ISSUE THREAD

**Issue by ligi** [syng-io/syng-client#38]
```
11-15 16:35:37.614  2158  2276 E AndroidRuntime: java.lang.SecurityException: Permission Denial: opening provider com.android.providers.contacts.ContactsProvider2 from ProcessR\
ecord{90b71f7 2158:io.syng/u0a62} (pid=2158, uid=10062) requires android.permission.READ_CONTACTS or android.permission.WRITE_CONTACTS
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1599)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1552)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.app.ActivityManagerProxy.getContentProvider(ActivityManagerNative.java:3550)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.app.ActivityThread.acquireProvider(ActivityThread.java:4778)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.app.ContextImpl$ApplicationContentResolver.acquireUnstableProvider(ContextImpl.java:2018)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.content.ContentResolver.acquireUnstableProvider(ContentResolver.java:1468)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:475)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at android.content.ContentResolver.query(ContentResolver.java:434)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at org.apache.cordova.contacts.ContactAccessorSdk5.search(ContactAccessorSdk5.java:177)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at org.apache.cordova.contacts.ContactManager$1.run(ContactManager.java:93)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-15 16:35:37.614  2158  2276 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:818)
```

**Comment by 0xc1c4da** [comment]
is this android 6?

**Comment by ligi** [comment]
yes

**Comment by 0xc1c4da** [comment]
Ah yes, Android 6.0 has new permission system, we've had the same error as well :) Thanks for making the issue! We'll work on it.

**Comment by karansharma27** [comment]
+1

**Comment by karansharma27** [comment]
Did you find any solution to this problem?

**Comment by ligi** [comment]
No - started my own wallet project (http://walleth.org)
